CXX=g++
CXXFLAGS=-I. -std=c++11
LDFLAGS=

.PHONY: clean

test_maximum_profit: maximum_profit.cpp test/test_maximum_profit.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_insersion_sort: insersion_sort.cpp test/test_insersion_sort.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_bubble_sort: bubble_sort.cpp test/test_bubble_sort.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_selection_sort: selection_sort.cpp test/test_selection_sort.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_stable_sort: stable_sort.cpp test/test_stable_sort.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_shell_sort: shell_sort.cpp test/test_shell_sort.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_stack: stack.cpp test/test_stack.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_queue: queue.cpp test/test_queue.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_double_linked_list: double_linked_list.cpp test/test_double_linked_list.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_areas_on_cross_section_diagram: areas_on_cross_section_diagram.cpp test/test_areas_on_cross_section_diagram.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_linear_search: linear_search.cpp test/test_linear_search.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_binary_search: binary_search.cpp test/test_binary_search.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_dictionary: dictionary.cpp test/test_dictionary.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_allocation: allocation.cpp test/test_allocation.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_exhaustive_search: exhaustive_search.cpp test/test_exhaustive_search.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_koch_curve: koch_curve.cpp test/test_koch_curve.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_merge_sort: merge_sort.cpp test/test_merge_sort.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_partition: partition.cpp test/test_partition.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_quick_sort: quick_sort.cpp test/test_quick_sort.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_counting_sort: counting_sort.cpp test/test_counting_sort.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_number_of_inversions: number_of_inversions.cpp test/test_number_of_inversions.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_rooted_trees: rooted_trees.cpp test/test_rooted_trees.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_binary_tree: binary_tree.cpp test/test_binary_tree.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

test_binary_search_tree: binary_search_tree.cpp test/test_binary_search_tree.cpp
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) $(LDFLAGS) -DTEST -lcriterion $^ -o $@

clean:
	$(RM) test_maximum_profit
